
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
-- =====================================================
-- CUSTOMER360 AI - MACHINE LEARNING SQL QUERIES
-- =====================================================

-- =====================================================
-- Q11. Number of Customers in Each Customer Segment
-- =====================================================

SELECT
    Customer_Segment,
    COUNT(*) AS Total_Customers
FROM customer
GROUP BY Customer_Segment
ORDER BY Total_Customers DESC;


-- =====================================================
-- Q12. Revenue Generated by Each Customer Segment
-- =====================================================

SELECT
    Customer_Segment,
    ROUND(SUM(purchase_amount),2) AS Total_Revenue
FROM customer
GROUP BY Customer_Segment
ORDER BY Total_Revenue DESC;


-- =====================================================
-- Q13. Average Purchase Amount of Each Customer Segment
-- =====================================================

SELECT
    Customer_Segment,
    ROUND(AVG(purchase_amount),2) AS Average_Purchase
FROM customer
GROUP BY Customer_Segment
ORDER BY Average_Purchase DESC;


-- =====================================================
-- Q14. Top 10 High Value Customers
-- =====================================================

SELECT
    customer_id,
    Customer_Segment,
    purchase_amount
FROM customer
ORDER BY purchase_amount DESC
LIMIT 10;


-- =====================================================
-- Q15. Customers Predicted to Churn
-- =====================================================

SELECT
    customer_id,
    Customer_Segment,
    purchase_amount,
    Churn
FROM customer
WHERE Churn = 1
ORDER BY purchase_amount DESC;


-- =====================================================
-- Q16. Number of Churn Customers in Each Segment
-- =====================================================

SELECT
    Customer_Segment,
    COUNT(*) AS Churn_Customers
FROM customer
WHERE Churn = 1
GROUP BY Customer_Segment
ORDER BY Churn_Customers DESC;


-- =====================================================
-- Q17. Revenue at Risk Due to Churn
-- =====================================================

SELECT
    ROUND(SUM(purchase_amount),2) AS Revenue_At_Risk
FROM customer
WHERE Churn = 1;


-- =====================================================
-- Q18. Premium Customers Likely to Churn
-- =====================================================

SELECT
    customer_id,
    purchase_amount,
    review_rating,
    previous_purchases
FROM customer
WHERE Customer_Segment = 'Premium Customer'
AND Churn = 1
ORDER BY purchase_amount DESC;


-- =====================================================
-- Q19. Most Frequently Recommended Products
-- =====================================================

SELECT
    Recommendation_1,
    COUNT(*) AS Recommendation_Count
FROM recommendations
GROUP BY Recommendation_1
ORDER BY Recommendation_Count DESC;

